# PngBlender2 configuration file
# Modes:
#   - noop
#     - No-op blend mode that returns the base image unchanged
#   - mix(weight)
#     - Mix the base image with the layer image by the given weight
#   - multiply
#     - Multiply the base image with the layer image
#   - mixbox(weight)
#     - Mix the base image with the layer image using the Mixbox algorithm
#   - penteract(average)
#     - Experimental blend mode that uses grayscale averaging, value normalization,
#       and dynamic range remapping to generate a new color transformation

paths:
  # Paths are resolved relative to main.py
  input: input
  output: output

blend:
  jupiterstone.pnm:
    modes:
      - penteract
    colors:
      - black.png
      - blackblue.png
      - blackbrown.png
      - blackcyan.png
      - blackgray.png
      - blackgreen.png
      - blacklightblue.png
      - blackmagenta.png
      - blackpink.png
      - blackpurple.png
      - blackred.png
      - blackyellow.png
      - blue.png
      - bluebrown.png
      - bluecyan.png
      - bluegray.png
      - bluelightblue.png
      - bluelightgray.png
      - bluelime.png
      - bluemagenta.png
      - blueorange.png
      - bluepink.png
      - bluepurple.png
      - brown.png
      - browncyan.png
      - browngray.png
      - browngreen.png
      - brownlightblue.png
      - brownlightgray.png
      - brownlime.png
      - brownmagenta.png
      - brownorange.png
      - brownpink.png
      - brownpurple.png
      - brownred.png
      - brownwhite.png
      - brownyellow.png
      - cyan.png
      - cyangray.png
      - cyangreen.png
      - cyanlightblue.png
      - cyanlightgray.png
      - cyanlime.png
      - cyanmagenta.png
      - cyanorange.png
      - cyanpink.png
      - cyanpurple.png
      - cyanwhite.png
      - cyanyellow.png
      - gray.png
      - graygreen.png
      - graylightblue.png
      - graylightgray.png
      - graylime.png
      - graymagenta.png
      - grayorange.png
      - graypink.png
      - graypurple.png
      - grayred.png
      - grayyellow.png
      - green.png
      - greenlightblue.png
      - greenlightgray.png
      - greenlime.png
      - greenmagenta.png
      - greenorange.png
      - greenpink.png
      - greenpurple.png
      - greenred.png
      - greenyellow.png
      - lightblue.png
      - lightbluelightgray.png
      - lightbluelime.png
      - lightbluemagenta.png
      - lightblueorange.png
      - lightbluepink.png
      - lightbluepurple.png
      - lightbluered.png
      - lightbluewhite.png
      - lightblueyellow.png
      - lightgray.png
      - lightgraylime.png
      - lightgraymagenta.png
      - lightgrayorange.png
      - lightgraypink.png
      - lightgraypurple.png
      - lightgrayred.png
      - lightgraywhite.png
      - lightgrayyellow.png
      - lime.png
      - limemagenta.png
      - limeorange.png
      - limepink.png
      - limepurple.png
      - limered.png
      - limewhite.png
      - limeyellow.png
      - magenta.png
      - magentaorange.png
      - magentapink.png
      - magentapurple.png
      - magentared.png
      - magentawhite.png
      - magentayellow.png
      - orange.png
      - orangepink.png
      - orangepurple.png
      - orangered.png
      - orangewhite.png
      - orangeyellow.png
      - pink.png
      - pinkred.png
      - pinkwhite.png
      - pinkyellow.png
      - purple.png
      - purplered.png
      - purplewhite.png
      - purpleyellow.png
      - red.png
      - white.png
      - whiteyellow.png
      - yellow.png
